# Generated by Django 2.1 on 2018-08-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parseddialogs',
            unique_together={('cus_id', 'dialog_time', 'session', 'event_id')},
        ),
    ]
