# Generated by Django 2.1 on 2018-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0003_auto_20180827_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='markedresult',
            index=models.Index(fields=['chat_date'], name='intent_mark_chat_da_4c0f68_idx'),
        ),
    ]
