# Generated by Django 2.1 on 2018-09-04 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0006_auto_20180904_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2018, 9, 4))),
                ('end_date', models.DateField(default=datetime.date(2018, 9, 4))),
            ],
        ),
        migrations.AddField(
            model_name='parseddialogs',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
