# Generated by Django 2.1 on 2018-09-04 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0007_auto_20180904_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_list', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'intent_marker_task_list',
                'managed': False,
            },
        ),
    ]
