# Generated by Django 2.1 on 2018-09-10 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0008_tasklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('user', models.CharField(max_length=32)),
                ('user_ip', models.CharField(max_length=15)),
                ('user_host', models.TextField()),
                ('request', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='taskdaterange',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 9, 10)),
        ),
        migrations.AlterField(
            model_name='taskdaterange',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 9, 10)),
        ),
    ]
