# Generated by Django 2.1 on 2018-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0011_auto_20180910_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
