# Generated by Django 2.1 on 2018-09-24 13:31

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_marker', '0013_auto_20180910_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedResultsReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_date', models.DateField()),
                ('client_id', models.CharField(max_length=6)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=255)),
                ('subtopic_id', models.IntegerField()),
                ('subtopic_name', models.CharField(max_length=255)),
                ('custom_topic', models.CharField(max_length=800)),
                ('custom_subtopic', models.CharField(max_length=800)),
                ('aggressive_client', models.BooleanField()),
                ('non_standard_question', models.BooleanField()),
                ('chosen_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'intent_marker_results_report',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='taskdaterange',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 9, 24)),
        ),
        migrations.AlterField(
            model_name='taskdaterange',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 9, 24)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='dte',
            field=models.DateField(default=datetime.date(2018, 9, 24)),
        ),
    ]
